controller:
  replicaCount: 1
  extraArgs:
    ingress-class: ingress-nginx
  publishService:
    enabled: true
  service:
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: /healthz
      service.beta.kubernetes.io/azure-load-balancer-resource-group: ${pip_rg_name} 
  ingressClassResource:
    name: ingress-nginx
  watchIngressWithoutClass: true