# SecretProviderClass example using workloads identity to access the key vault
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-identity # needs to be unique per namespace
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"          
    clientID: "${uai-aks-clientid}"                       # aks_msi_client_id
    keyvaultName: "akskv01-rg-prd-0000111"                # Set to the name of your key vault
    cloudName: "AzurePublicCloud"                         # [OPTIONAL for Azure] if not provided, the Azure environment defaults to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: AKS-TITLE
          objectType: secret
          objectVersion: ""
    tenantId: "${tenant_id}"        # The tenant ID of the key vault

  secretObjects:
  - secretName: so-aks
    type: Opaque
    data:
    - objectName: AKS-TITLE
      key: aks-title