apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: "${uai-aks-clientid}"
  labels:
    azure.workload.identity/use: "true"
  name: "aks01-identity-sa"
  namespace: "default"
